## Classifying Passwords Strength With Machine Learning in Python

In [ ]:
# EDA Packages
import pandas as pd

In [ ]:
# Load Passwordlist
pswd_data = pd.read_csv("/content/data.csv",error_bad_lines=False)


b'Skipping line 2810: expected 2 fields, saw 5\nSkipping line 4641: expected 2 fields, saw 5\nSkipping line 7171: expected 2 fields, saw 5\nSkipping line 11220: expected 2 fields, saw 5\nSkipping line 13809: expected 2 fields, saw 5\nSkipping line 14132: expected 2 fields, saw 5\nSkipping line 14293: expected 2 fields, saw 5\nSkipping line 14865: expected 2 fields, saw 5\nSkipping line 17419: expected 2 fields, saw 5\nSkipping line 22801: expected 2 fields, saw 5\nSkipping line 25001: expected 2 fields, saw 5\nSkipping line 26603: expected 2 fields, saw 5\nSkipping line 26742: expected 2 fields, saw 5\nSkipping line 29702: expected 2 fields, saw 5\nSkipping line 32767: expected 2 fields, saw 5\nSkipping line 32878: expected 2 fields, saw 5\nSkipping line 35643: expected 2 fields, saw 5\nSkipping line 36550: expected 2 fields, saw 5\nSkipping line 38732: expected 2 fields, saw 5\nSkipping line 40567: expected 2 fields, saw 5\nSkipping line 40576: expected 2 fields, saw 5\nSkipping line 

In [ ]:
pswd_data.head()

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [ ]:
pswd_data['strength'].unique()

array([1, 2, 0])

In [ ]:
pswd_data.isna().sum()

password    1
strength    0
dtype: int64

In [ ]:
pswd_data.dropna(inplace=True)

In [ ]:
pswd_data.isna().sum()

password    0
strength    0
dtype: int64

In [ ]:
import numpy as np

In [ ]:
pswd = np.array(pswd_data)

In [ ]:
pswd

array([['kzde5577', 1],
       ['kino3434', 1],
       ['visi7k1yr', 1],
       ...,
       ['184520socram', 1],
       ['marken22a', 1],
       ['fxx4pw4g', 1]], dtype=object)

In [ ]:
import random

In [ ]:
# Shuffle data 
random.shuffle(pswd)

In [ ]:
# Grouping our data into features and labels
# y = labels
ylabels  = [s[1] for s in pswd]
allpasswords = [s[0] for s in pswd]

In [ ]:
ylabels
len(ylabels)

669639

In [ ]:
len(allpasswords)

669639

### Data Vectorization Using TfidVectorizer
#### Create A tokenizer
 + Use either the entire password
 + Use each character

In [ ]:
def createTokens(f):
    tokens = []
    for i in f:
        tokens.append(i)
    return tokens

In [ ]:
# Machine Learning Packages
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
# Using Default Tokenizer
# Using Custom Tokenizer
vectorizer = TfidfVectorizer(tokenizer=createTokens)

In [ ]:
# Store vectors into X variable as Our X allpasswords
X = vectorizer.fit_transform(allpasswords)

##### Splitting Data Into Train and Test at 80/20

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, ylabels, test_size=0.2, random_state=42)	

In [ ]:
# Model Building
#using logistic regression
# Multi_class for fast algorithm
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()	
clf.fit(X_train, y_train)


DecisionTreeClassifier()

#### Accuracy of Our Model

In [ ]:
print("Accuracy :",clf.score(X_train, y_train))

Accuracy : 0.9998114655103219


In [ ]:
y_pred=clf.predict(X_test)
y_pred

array([0, 0, 1, ..., 1, 1, 0])

In [ ]:
print("Accuracy :",clf.score(X_test, y_test))

Accuracy : 0.9738516217669195


#### Predicting With Our Model

In [ ]:
X_predict = ['drshsyqb*',
             'python'
             'littledotsK18@#',
             'password##@',
             'ajd1348#28t**',
             'gtddsdsaa',
             'silasaw',
             '123456',
             'abcdef']

X_predict = vectorizer.transform(X_predict)
y_Predict = clf.predict(X_predict)
print(y_Predict)

[1 2 1 2 1 0 0 2]
